version: "2"
services:
  nlp_note:
    command: /bin/bash -c "jupyter notebook --ip=0.0.0.0 --allow-root --port=18888"
    build:
      context: ./docker
    volumes:
      - "./notebooks/:/home/work"
    ports:
      - "18888:18888"
  redis:
    image: "redis:alpine"
